import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        bonzini: {
          purple: "hsl(var(--bonzini-purple))",
          "purple-light": "hsl(var(--bonzini-purple-light))",
          "purple-dark": "hsl(var(--bonzini-purple-dark))",
          "purple-glow": "hsl(var(--bonzini-purple-glow))",
        },
        admin: {
          sidebar: "hsl(var(--admin-sidebar))",
          "sidebar-foreground": "hsl(var(--admin-sidebar-foreground))",
          "sidebar-accent": "hsl(var(--admin-sidebar-accent))",
          "sidebar-muted": "hsl(var(--admin-sidebar-muted))",
        },
        chart: {
          emerald: "hsl(var(--chart-emerald))",
          blue: "hsl(var(--chart-blue))",
          amber: "hsl(var(--chart-amber))",
          red: "hsl(var(--chart-red))",
          purple: "hsl(var(--chart-purple))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        lp: {
          bg:              "#050208",
          violet:          "#a64af7",
          "violet-glow":   "#c084fc",
          gold:            "#f3a745",
          orange:          "#fe560d",
          muted:           "#8b82a0",
          dim:             "#3d3555",
          surface:         "#0f0b18",
          "surface-light": "#1a1428",
          alipay:          "#1677ff",
          wechat:          "#07c160",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ['"Syne"', "sans-serif"],
        body: ['"DM Sans"', "sans-serif"],
      },
      fontSize: {
        balance: ["3rem", { lineHeight: "1", fontWeight: "700" }],
        "balance-sm": ["2rem", { lineHeight: "1", fontWeight: "700" }],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        card: "var(--shadow-card)",
        purple: "var(--shadow-purple)",
        elevated: "var(--shadow-lg)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-down": { from: { opacity: "0", transform: "translateY(-10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-right": { from: { opacity: "0", transform: "translateX(-10px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "slide-left": { from: { opacity: "0", transform: "translateX(30px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        shake: { "0%, 100%": { transform: "translateX(0)" }, "20%": { transform: "translateX(-4px)" }, "40%": { transform: "translateX(4px)" }, "60%": { transform: "translateX(-3px)" }, "80%": { transform: "translateX(3px)" } },
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        "logo-entrance": { from: { opacity: "0", transform: "scale(0.8)" }, to: { opacity: "1", transform: "scale(1)" } },
        "fade-out": { from: { opacity: "1" }, to: { opacity: "0" } },
        "kpi-entrance": { from: { opacity: "0", transform: "scale(0.97)" }, to: { opacity: "1", transform: "scale(1)" } },
        "deposit-pulse": { "0%, 100%": { opacity: "0.7", transform: "scale(1)" }, "50%": { opacity: "1", transform: "scale(1.05)" } },
        "glow-pulse": { "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.2)" }, "50%": { boxShadow: "0 0 20px 4px hsl(var(--primary) / 0.15)" } },
        "success-glow": { "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--success) / 0.2)" }, "50%": { boxShadow: "0 0 20px 4px hsl(var(--success) / 0.15)" } },
        "lp-spin": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "lp-pulse": { "0%, 100%": { opacity: "0.12", transform: "scale(1)" }, "50%": { opacity: "0.2", transform: "scale(1.1)" } },
        "lp-ticker": { from: { transform: "translateX(0)" }, to: { transform: "translateX(-33.33%)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
        "slide-down": "slide-down 0.3s ease-out",
        "fade-in": "fade-in 0.4s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "slide-right": "slide-right 0.3s ease-out",
        "slide-left": "slide-left 0.35s ease-out",
        shake: "shake 0.4s ease-in-out",
        float: "float 6s ease-in-out infinite",
        "logo-entrance": "logo-entrance 0.6s ease-out",
        "fade-out": "fade-out 0.3s ease-in",
        "kpi-entrance": "kpi-entrance 0.4s ease-out",
        "deposit-pulse": "deposit-pulse 1.5s ease-in-out infinite",
        shimmer: "shimmer 2s infinite linear",
        "glow-pulse": "glow-pulse 2.5s ease-in-out infinite",
        "success-glow": "success-glow 2.5s ease-in-out infinite",
        "lp-spin": "lp-spin 20s linear infinite",
        "lp-pulse": "lp-pulse 6s ease-in-out infinite",
        "lp-ticker": "lp-ticker 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
