"""Real RMS of the team quotes (Q1–Q6), one value per output frame (30 Hz), 0..1 → overlay/scenes/15_qrms.js.
Index = frame offset from the segment start (TL.seg(q).start)."""
import json, os, numpy as np, soundfile as sf
E = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
tl = json.load(open(os.path.join(E, 'data', 'timeline.json')))
x, sr = sf.read(os.path.join(E, 'audio', 'voice_sp.wav'), dtype='float32'); x = x.mean(1) if x.ndim > 1 else x
out = {}
for s in tl['segments']:
    if s['kind'] != 'sp': continue
    a, b = int(s['start'] * sr), int(s['end'] * sr); y = x[a:b]; hop = sr // 30
    r = np.array([np.sqrt(np.mean(y[i:i + hop] ** 2) + 1e-12) for i in range(0, len(y), hop)])
    db = 20 * np.log10(r + 1e-9); lo, hi = np.percentile(db, 10), np.percentile(db, 98)
    out[s['id']] = [round(float(v), 2) for v in np.clip((db - lo) / max(hi - lo, 1e-6), 0, 1)]
open(os.path.join(E, 'overlay', 'scenes', '15_qrms.js'), 'w').write(
    "'use strict';\n// generated by lib/q_rms.py — real RMS of the team quotes, 30 Hz, 0..1, index = frames since TL.seg(q).start\nwindow.Q_RMS = " + json.dumps(out) + ";\n")
print({k: len(v) for k, v in out.items()})
